## Bivariate and Multivariate Analysis

In [87]:
import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from IPython.display import display
import ipywidgets as widgets
import plotly.express as px

pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", 1000)

### Feature engineering

In [42]:
zip_file_path = "Data/LFS_JV_CPI.csv.zip"
csv_file_name = "LFS_JV_CPI.csv"  

# Open and read the zipped CSV file
with zipfile.ZipFile(zip_file_path, "r") as z:
    with z.open(csv_file_name) as f:
        df = pd.read_csv(f)

df.head()

   survey_month  lf_status  province  cmetrop_area  5y_age  2_3y_age  sex  marital_stat  education  multiple_jobh  work_lasty  ft_pt_last  main_class_worker  immigration_stat  NAICS_21  NOC_10  NOC_43  rsn_absent_fullwk  weeks_absent  paid_for_absence  usualhrs_main  actualhrs_main  ft_pt_main  usualhrs_all  actualhrs_all  hrs_away  rsn_away  paid_overtime  unpaid_overtime  hrs_overtime  rsn_pt  current_tenure  prev_tenure  hourly_wage  union_stat  job_permenancy  estab_size  firm_size  duration_unemp  flow_to_unemp  job_seekers_temp_layoffs_status  rsn_left_old  rsn_left_new  duration_jobless  availability  prior_activity  rsn_not_looking  temp_layoff_looked  student_status  econ_fam_type  final_wt    REF_DATE            JV_industry          comb_industry  Job vacancies (#)  Payroll employees (#)  Job vacancy rate (Percent)  Inflation_Rate_MoM
0             1          4        24             0      12       NaN    2             1          2            NaN         2.0         NaN                NaN                 3       NaN     NaN     NaN                NaN           NaN               NaN            NaN             NaN         NaN           NaN            NaN       NaN       NaN            NaN              NaN           NaN     NaN             NaN          NaN          NaN         NaN             NaN         NaN        NaN             NaN            NaN                              NaN           NaN           NaN             240.0           NaN             NaN              NaN                 NaN             NaN             11       141  2024-01-01                    NaN                    NaN                NaN                    NaN                         NaN                 NaN
1             1          4        47             0       4       NaN    1             6          2            NaN         3.0         NaN                NaN                 3       NaN     NaN     NaN                NaN           NaN               NaN            NaN             NaN         NaN           NaN            NaN       NaN       NaN            NaN              NaN           NaN     NaN             NaN          NaN          NaN         NaN             NaN         NaN        NaN             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0             18       200  2024-01-01                    NaN                    NaN                NaN                    NaN                         NaN                 NaN
2             1          1        10             0       1       2.0    1             6          2            1.0         NaN         NaN                2.0                 3      10.0     7.0    33.0                NaN           NaN               NaN          250.0           220.0         2.0         250.0          220.0       0.0       NaN            0.0              0.0           0.0     6.0            41.0          NaN         15.0         3.0             1.0         1.0        3.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0              4        34  2024-01-01   Retail trade [44-45]   Retail trade [44-45]            67005.0              2009425.0                         3.2           -0.125392
3             1          1        35             4      12       NaN    1             2          4            1.0         NaN         NaN                2.0                 3       8.0    10.0    42.0                NaN           NaN               NaN          400.0           400.0         1.0         400.0          400.0       0.0       NaN            0.0              0.0           0.0     NaN           178.0          NaN         24.5         3.0             1.0         2.0        2.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             NaN              2       275  2024-01-01  Manufacturing [31-33]  Manufacturing [31-33]            40030.0              1563315.0                         2.5           -0.125392
4             1          1        35             0       6       NaN    1             1          4            1.0         NaN         NaN                2.0                 3       6.0     8.0    35.0                NaN           NaN               NaN          450.0           420.0         1.0         450.0          420.0       0.0       NaN            0.0              0.0           0.0     NaN           212.0          NaN         28.0         3.0             1.0         1.0        1.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0              3       231  2024-01-01      Construction [23]      Construction [23]            52785.0              1171530.0                         4.3           -0.125392

In [44]:
df.describe()

       survey_month     lf_status      province  cmetrop_area        5y_age       2_3y_age           sex  marital_stat     education  multiple_jobh     work_lasty    ft_pt_last  main_class_worker  immigration_stat       NAICS_21         NOC_10         NOC_43  rsn_absent_fullwk  weeks_absent  paid_for_absence  usualhrs_main  actualhrs_main     ft_pt_main   usualhrs_all  actualhrs_all       hrs_away      rsn_away  paid_overtime  unpaid_overtime   hrs_overtime         rsn_pt  current_tenure   prev_tenure    hourly_wage     union_stat  job_permenancy     estab_size      firm_size  duration_unemp  flow_to_unemp  job_seekers_temp_layoffs_status  rsn_left_old  rsn_left_new  duration_jobless  availability  prior_activity  rsn_not_looking  temp_layoff_looked  student_status  econ_fam_type      final_wt  Job vacancies (#)  Payroll employees (#)  Job vacancy rate (Percent)  Inflation_Rate_MoM
count  1.230968e+06  1.230968e+06  1.230968e+06  1.230968e+06  1.230968e+06  244199.000000  1.230968e+06  1.230968e+06  1.230968e+06  723871.000000  507097.000000  81783.000000      805654.000000      1.230968e+06  805654.000000  805654.000000  805654.000000       66782.000000  66782.000000      60592.000000  723871.000000   723871.000000  723871.000000  723871.000000  723871.000000  570354.000000  92546.000000  570354.000000    570354.000000  570354.000000  131150.000000   723871.000000  81783.000000  627171.000000  627171.000000   627171.000000  627171.000000  627171.000000    45388.000000   47666.000000                     47666.000000  81783.000000  81783.000000     424660.000000  53630.000000    43608.000000     15385.000000          1780.00000   916425.000000   1.230968e+06  1.230968e+06      805654.000000           8.056540e+05               805654.000000       805654.000000
mean   6.025369e+00  2.251379e+00  3.457474e+01  1.748638e+00  7.223975e+00       3.595928  1.513340e+00  2.875877e+00  3.464106e+00       1.056346       2.001290      1.343066           2.122299      2.703124e+00      13.177188       5.188987      22.851064           1.880102     12.832889          1.505578     357.599217      320.242517       1.181179     365.613684     327.339157      17.221597      2.108162       8.161996         6.102193      14.264153       4.113206       93.934832     62.012142      34.561476       2.366508        1.241582       2.206685       2.993310       17.034503       4.516658                         1.358683      3.306763      7.555910        109.299428      1.937050        1.586934         2.432629             1.63427        1.143036   6.276759e+00  2.999871e+02       45945.309099           1.306506e+06                    3.182208            0.142423
std    3.154626e+00  1.415006e+00  1.459426e+01  2.788208e+00  3.601182e+00       1.730339  4.998222e-01  2.174572e+00  1.631581e+00       0.230588       0.569071      0.474736           1.189413      5.903988e-01       5.054034       2.653736      12.741198           1.118146     21.103848          0.499973     116.315650      161.566811       0.385166     122.009995     166.219091      49.527234      1.053424      36.033017        27.985685      45.093916       1.824979       84.187264     81.983072      18.774372       0.919603        0.708829       1.047010       1.163849       20.501596       2.085940                         0.570630      1.457374      3.455691         88.625961      0.242875        0.991796         1.926234             0.48177        0.400644   5.427379e+00  2.769295e+02       35916.308631           6.371243e+05                    1.142057            0.121554
min    1.000000e+00  1.000000e+00  1.000000e+01  0.000000e+00  1.000000e+00       1.000000  1.000000e+00  1.000000e+00  0.000000e+00       1.000000       1.000000      1.000000           1.000000      1.000000e+00       1.000000       1.000000       1.000000           0.000000      1.000000          1.000000       1.000000        0.000000       1.000000       1.000000       0.000000       0.000000      0.000000       0.000000         0.000000       0.000000       0.000000        1.000000      1.000000       5.770000       1.000000        1.000000       1.000000       1.000000        1.000000       1.000000                         1.000000      0.000000      0.000000          1.000000      1.000000        0.000000         0.000000             1.00000        1.000000   1.000000e+00  1.000000e+00        1485.000000           1.332950e+05                    1.100000           -0.125392
25%    3.000000e+00  1.000000e+00  2.400000e+01  0.000000e+00  4.000000e+00       2.000000  1.000000e+00  1.000000e+00  2.000000e+00       1.000000       2.000000      1.000000           2.000000      3.000000e+00      10.000000       3.000000      10.000000           1.000000      1.000000          1.000000     325.000000      240.000000       1.000000     350.000000     240.000000       0.000000      1.000000       0.000000         0.000000       0.000000       4.000000       21.000000      5.000000      21.000000       1.000000        1.000000       1.000000       2.000000        4.000000       2.000000                         1.000000      3.000000      5.000000         24.000000      2.000000        1.000000         1.000000             1.00000        1.000000   2.000000e+00  1.300000e+02       20750.000000           8.398100e+05                    2.300000            0.062035
50%    6.000000e+00  1.000000e+00  3.500000e+01  0.000000e+00  7.000000e+00       4.000000  2.000000e+00  2.000000e+00  4.000000e+00       1.000000       2.000000      1.000000           2.000000      3.000000e+00      14.000000       5.000000      24.000000           2.000000      3.000000          2.000000     400.000000      375.000000       1.000000     400.000000     375.000000       0.000000      3.000000       0.000000         0.000000       0.000000       4.000000       63.000000     19.000000      29.650000       3.000000        1.000000       2.000000       4.000000        8.000000       5.000000                         1.000000      4.000000      7.000000         90.000000      2.000000        1.000000         2.000000             2.00000        1.000000   4.000000e+00  2.110000e+02       37235.000000           1.225550e+06                    3.000000            0.125549
75%    9.000000e+00  4.000000e+00  4.700000e+01  4.000000e+00  1.100000e+01       5.000000  2.000000e+00  6.000000e+00  5.000000e+00       1.000000       2.000000      2.000000           2.000000      3.000000e+00      17.000000       7.000000      34.000000           3.000000     14.000000          2.000000     400.000000      400.000000       1.000000     400.000000     400.000000       0.000000      3.000000       0.000000         0.000000       0.000000       5.000000      163.000000     84.000000      43.085000       3.000000        1.000000       3.000000       4.000000       20.000000       6.000000                         2.000000      4.000000     10.000000        198.000000      2.000000        3.000000         4.000000             2.00000        1.000000   1.100000e+01  3.520000e+02       53785.000000           1.992995e+06                    3.945648            0.249688
max    1.100000e+01  4.000000e+00  5.900000e+01  9.000000e+00  1.200000e+01       6.000000  2.000000e+00  6.000000e+00  6.000000e+00       2.000000       3.000000      2.000000           7.000000      3.000000e+00      21.000000      10.000000      43.000000           3.000000     99.000000          2.000000     990.000000      990.000000       2.000000     990.000000     990.000000     990.000000      4.000000     990.000000       990.000000     990.000000       7.000000      240.000000    240.000000     230.770000       3.000000        4.000000       4.000000       4.000000       99.000000       8.000000                         3.000000      5.000000     13.000000        240.000000      2.000000        3.000000         6.000000             2.00000        3.000000   1.800000e+01  3.403000e+03      144260.000000           2.411235e+06                    5.900000            0.309981

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230968 entries, 0 to 1230967
Data columns (total 58 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   survey_month                     1230968 non-null  int64
 1   lf_status                        1230968 non-null  int64
 2   province                         1230968 non-null  int64
 3   cmetrop_area                     1230968 non-null  int64
 4   5y_age                           1230968 non-null  int64
 5   2_3y_age                         244199 non-null   float64
 6   sex                              1230968 non-null  int64
 7   marital_stat                     1230968 non-null  int64
 8   education                        1230968 non-null  int64
 9   multiple_jobh                    723871 non-null   float64
 10  work_lasty                       507097 non-null   float64
 11  ft_pt_last                       81783 non-null    float64
 12  main_class_worker                805654 non-null   float64
 13  immigration_stat                 1230968 non-null  int64
 14  NAICS_21                         805654 non-null   float64
 15  NOC_10                           805654 non-null   float64
 16  NOC_43                           805654 non-null   float64
 17  rsn_absent_fullwk                66782 non-null    float64
 18  weeks_absent                     66782 non-null    float64
 19  paid_for_absence                 60592 non-null    float64
 20  usualhrs_main                    723871 non-null   float64
 21  actualhrs_main                   723871 non-null   float64
 22  ft_pt_main                       723871 non-null   float64
 23  usualhrs_all                     723871 non-null   float64
 24  actualhrs_all                    723871 non-null   float64
 25  hrs_away                         570354 non-null   float64
 26  rsn_away                         92546 non-null    float64
 27  paid_overtime                    570354 non-null   float64
 28  unpaid_overtime                  570354 non-null   float64
 29  hrs_overtime                     570354 non-null   float64
 30  rsn_pt                           131150 non-null   float64
 31  current_tenure                   723871 non-null   float64
 32  prev_tenure                      81783 non-null    float64
 33  hourly_wage                      627171 non-null   float64
 34  union_stat                       627171 non-null   float64
 35  job_permenancy                   627171 non-null   float64
 36  estab_size                       627171 non-null   float64
 37  firm_size                        627171 non-null   float64
 38  duration_unemp                   45388 non-null    float64
 39  flow_to_unemp                    47666 non-null    float64
 40  job_seekers_temp_layoffs_status  47666 non-null    float64
 41  rsn_left_old                     81783 non-null    float64
 42  rsn_left_new                     81783 non-null    float64
 43  duration_jobless                 424660 non-null   float64
 44  availability                     53630 non-null    float64
 45  prior_activity                   43608 non-null    float64
 46  rsn_not_looking                  15385 non-null    float64
 47  temp_layoff_looked               1780 non-null     float64
 48  student_status                   916425 non-null   float64
 49  econ_fam_type                    1230968 non-null  int64
 50  final_wt                         1230968 non-null  int64
 51  REF_DATE                         1230968 non-null  object
 52  JV_industry                      805654 non-null   object
 53  comb_industry                    805654 non-null   object
 54  Job vacancies (#)                805654 non-null   float64
 55  Payroll employees (#)            805654 non-null   float64
 56  Job vacancy rate (Percent)       805654 non-null   float64
 57  Inflation_Rate_MoM               805654 non-null   float64
dtypes: float64(44), int64(11), object(3)
memory usage: 544.7+ MB

In [66]:
# Calculating Labour force participation rate 
labour_force = df[df['lf_status'].isin([1, 2, 3])].groupby('REF_DATE')['5y_age'].sum().reset_index()
labour_force.rename(columns={'5y_age': 'labour_force'})

# Get total working-age population 
working_age_pop = df.groupby('REF_DATE')['5y_age'].sum()

# Calculate Labour Force Participation Rate (LFPR)
lf_participation = (labour_force / working_age_pop) * 100

LFPR_monthly = lf_participation.reset_index().rename(columns={'5y_age': 'LFPR_rate'})

In [54]:
df1 = df.merge(LFPR_monthly, on="REF_DATE", how="left")

df1.head()

   survey_month  lf_status  province  cmetrop_area  5y_age  2_3y_age  sex  marital_stat  education  multiple_jobh  work_lasty  ft_pt_last  main_class_worker  immigration_stat  NAICS_21  NOC_10  NOC_43  rsn_absent_fullwk  weeks_absent  paid_for_absence  usualhrs_main  actualhrs_main  ft_pt_main  usualhrs_all  actualhrs_all  hrs_away  rsn_away  paid_overtime  unpaid_overtime  hrs_overtime  rsn_pt  current_tenure  prev_tenure  hourly_wage  union_stat  job_permenancy  estab_size  firm_size  duration_unemp  flow_to_unemp  job_seekers_temp_layoffs_status  rsn_left_old  rsn_left_new  duration_jobless  availability  prior_activity  rsn_not_looking  temp_layoff_looked  student_status  econ_fam_type  final_wt    REF_DATE            JV_industry          comb_industry  Job vacancies (#)  Payroll employees (#)  Job vacancy rate (Percent)  Inflation_Rate_MoM  LFPR_rate
0             1          4        24             0      12       NaN    2             1          2            NaN         2.0         NaN                NaN                 3       NaN     NaN     NaN                NaN           NaN               NaN            NaN             NaN         NaN           NaN            NaN       NaN       NaN            NaN              NaN           NaN     NaN             NaN          NaN          NaN         NaN             NaN         NaN        NaN             NaN            NaN                              NaN           NaN           NaN             240.0           NaN             NaN              NaN                 NaN             NaN             11       141  2024-01-01                    NaN                    NaN                NaN                    NaN                         NaN                 NaN  52.475504
1             1          4        47             0       4       NaN    1             6          2            NaN         3.0         NaN                NaN                 3       NaN     NaN     NaN                NaN           NaN               NaN            NaN             NaN         NaN           NaN            NaN       NaN       NaN            NaN              NaN           NaN     NaN             NaN          NaN          NaN         NaN             NaN         NaN        NaN             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0             18       200  2024-01-01                    NaN                    NaN                NaN                    NaN                         NaN                 NaN  52.475504
2             1          1        10             0       1       2.0    1             6          2            1.0         NaN         NaN                2.0                 3      10.0     7.0    33.0                NaN           NaN               NaN          250.0           220.0         2.0         250.0          220.0       0.0       NaN            0.0              0.0           0.0     6.0            41.0          NaN         15.0         3.0             1.0         1.0        3.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0              4        34  2024-01-01   Retail trade [44-45]   Retail trade [44-45]            67005.0              2009425.0                         3.2           -0.125392  52.475504
3             1          1        35             4      12       NaN    1             2          4            1.0         NaN         NaN                2.0                 3       8.0    10.0    42.0                NaN           NaN               NaN          400.0           400.0         1.0         400.0          400.0       0.0       NaN            0.0              0.0           0.0     NaN           178.0          NaN         24.5         3.0             1.0         2.0        2.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             NaN              2       275  2024-01-01  Manufacturing [31-33]  Manufacturing [31-33]            40030.0              1563315.0                         2.5           -0.125392  52.475504
4             1          1        35             0       6       NaN    1             1          4            1.0         NaN         NaN                2.0                 3       6.0     8.0    35.0                NaN           NaN               NaN          450.0           420.0         1.0         450.0          420.0       0.0       NaN            0.0              0.0           0.0     NaN           212.0          NaN         28.0         3.0             1.0         1.0        1.0             NaN            NaN                              NaN           NaN           NaN               NaN           NaN             NaN              NaN                 NaN             1.0              3       231  2024-01-01      Construction [23]      Construction [23]            52785.0              1171530.0                         4.3           -0.125392  52.475504

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230968 entries, 0 to 1230967
Data columns (total 59 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   survey_month                     1230968 non-null  int64
 1   lf_status                        1230968 non-null  int64
 2   province                         1230968 non-null  int64
 3   cmetrop_area                     1230968 non-null  int64
 4   5y_age                           1230968 non-null  int64
 5   2_3y_age                         244199 non-null   float64
 6   sex                              1230968 non-null  int64
 7   marital_stat                     1230968 non-null  int64
 8   education                        1230968 non-null  int64
 9   multiple_jobh                    723871 non-null   float64
 10  work_lasty                       507097 non-null   float64
 11  ft_pt_last                       81783 non-null    float64
 12  main_class_worker                805654 non-null   float64
 13  immigration_stat                 1230968 non-null  int64
 14  NAICS_21                         805654 non-null   float64
 15  NOC_10                           805654 non-null   float64
 16  NOC_43                           805654 non-null   float64
 17  rsn_absent_fullwk                66782 non-null    float64
 18  weeks_absent                     66782 non-null    float64
 19  paid_for_absence                 60592 non-null    float64
 20  usualhrs_main                    723871 non-null   float64
 21  actualhrs_main                   723871 non-null   float64
 22  ft_pt_main                       723871 non-null   float64
 23  usualhrs_all                     723871 non-null   float64
 24  actualhrs_all                    723871 non-null   float64
 25  hrs_away                         570354 non-null   float64
 26  rsn_away                         92546 non-null    float64
 27  paid_overtime                    570354 non-null   float64
 28  unpaid_overtime                  570354 non-null   float64
 29  hrs_overtime                     570354 non-null   float64
 30  rsn_pt                           131150 non-null   float64
 31  current_tenure                   723871 non-null   float64
 32  prev_tenure                      81783 non-null    float64
 33  hourly_wage                      627171 non-null   float64
 34  union_stat                       627171 non-null   float64
 35  job_permenancy                   627171 non-null   float64
 36  estab_size                       627171 non-null   float64
 37  firm_size                        627171 non-null   float64
 38  duration_unemp                   45388 non-null    float64
 39  flow_to_unemp                    47666 non-null    float64
 40  job_seekers_temp_layoffs_status  47666 non-null    float64
 41  rsn_left_old                     81783 non-null    float64
 42  rsn_left_new                     81783 non-null    float64
 43  duration_jobless                 424660 non-null   float64
 44  availability                     53630 non-null    float64
 45  prior_activity                   43608 non-null    float64
 46  rsn_not_looking                  15385 non-null    float64
 47  temp_layoff_looked               1780 non-null     float64
 48  student_status                   916425 non-null   float64
 49  econ_fam_type                    1230968 non-null  int64
 50  final_wt                         1230968 non-null  int64
 51  REF_DATE                         1230968 non-null  object
 52  JV_industry                      805654 non-null   object
 53  comb_industry                    805654 non-null   object
 54  Job vacancies (#)                805654 non-null   float64
 55  Payroll employees (#)            805654 non-null   float64
 56  Job vacancy rate (Percent)       805654 non-null   float64
 57  Inflation_Rate_MoM               805654 non-null   float64
 58  lf_participation_rate            1230968 non-null  float64
dtypes: float64(45), int64(11), object(3)
memory usage: 554.1+ MB

In [78]:
# Calculating Labour force participation rate 
labour_force = df1[df1['lf_status'].isin([1, 2, 3])].groupby('REF_DATE')['5y_age'].sum().reset_index()
labour_force.rename(columns={'5y_age': 'labour_force'}, inplace=True)

# Filter unemployed individuals 
unemployed_df = df1[df1["lf_status"] == 3]

# Count unemployed per month
unemployed_per_month = unemployed_df.groupby("REF_DATE")['5y_age'].sum().reset_index()
unemployed_per_month.rename(columns={"5y_age": "Unemployed"}, inplace=True)

unemployment_rate_df = unemployed_per_month.merge(labour_force, on="REF_DATE")

# Compute unemployment rate
unemployment_rate_df["Unemployment_Rate"] = (unemployment_rate_df["Unemployed"] / unemployment_rate_df["labour_force"]) * 100

# Display results
print(unemployment_rate_df.head())

     REF_DATE  Unemployed  labour_force  Unemployment_Rate
0  2024-01-01       22201        415797           5.339384
1  2024-02-01       21972        419360           5.239412
2  2024-03-01       23098        424964           5.435284
3  2024-04-01       22174        427765           5.183687
4  2024-05-01       20619        433064           4.761190

In [82]:
# Merge unemployment rate into merged_df
df_final = df1.merge(unemployment_rate_df[["REF_DATE", "Unemployment_Rate"]], on="REF_DATE", how="left")

In [84]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230968 entries, 0 to 1230967
Data columns (total 60 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   survey_month                     1230968 non-null  int64
 1   lf_status                        1230968 non-null  int64
 2   province                         1230968 non-null  int64
 3   cmetrop_area                     1230968 non-null  int64
 4   5y_age                           1230968 non-null  int64
 5   2_3y_age                         244199 non-null   float64
 6   sex                              1230968 non-null  int64
 7   marital_stat                     1230968 non-null  int64
 8   education                        1230968 non-null  int64
 9   multiple_jobh                    723871 non-null   float64
 10  work_lasty                       507097 non-null   float64
 11  ft_pt_last                       81783 non-null    float64
 12  main_class_worker                805654 non-null   float64
 13  immigration_stat                 1230968 non-null  int64
 14  NAICS_21                         805654 non-null   float64
 15  NOC_10                           805654 non-null   float64
 16  NOC_43                           805654 non-null   float64
 17  rsn_absent_fullwk                66782 non-null    float64
 18  weeks_absent                     66782 non-null    float64
 19  paid_for_absence                 60592 non-null    float64
 20  usualhrs_main                    723871 non-null   float64
 21  actualhrs_main                   723871 non-null   float64
 22  ft_pt_main                       723871 non-null   float64
 23  usualhrs_all                     723871 non-null   float64
 24  actualhrs_all                    723871 non-null   float64
 25  hrs_away                         570354 non-null   float64
 26  rsn_away                         92546 non-null    float64
 27  paid_overtime                    570354 non-null   float64
 28  unpaid_overtime                  570354 non-null   float64
 29  hrs_overtime                     570354 non-null   float64
 30  rsn_pt                           131150 non-null   float64
 31  current_tenure                   723871 non-null   float64
 32  prev_tenure                      81783 non-null    float64
 33  hourly_wage                      627171 non-null   float64
 34  union_stat                       627171 non-null   float64
 35  job_permenancy                   627171 non-null   float64
 36  estab_size                       627171 non-null   float64
 37  firm_size                        627171 non-null   float64
 38  duration_unemp                   45388 non-null    float64
 39  flow_to_unemp                    47666 non-null    float64
 40  job_seekers_temp_layoffs_status  47666 non-null    float64
 41  rsn_left_old                     81783 non-null    float64
 42  rsn_left_new                     81783 non-null    float64
 43  duration_jobless                 424660 non-null   float64
 44  availability                     53630 non-null    float64
 45  prior_activity                   43608 non-null    float64
 46  rsn_not_looking                  15385 non-null    float64
 47  temp_layoff_looked               1780 non-null     float64
 48  student_status                   916425 non-null   float64
 49  econ_fam_type                    1230968 non-null  int64
 50  final_wt                         1230968 non-null  int64
 51  REF_DATE                         1230968 non-null  object
 52  JV_industry                      805654 non-null   object
 53  comb_industry                    805654 non-null   object
 54  Job vacancies (#)                805654 non-null   float64
 55  Payroll employees (#)            805654 non-null   float64
 56  Job vacancy rate (Percent)       805654 non-null   float64
 57  Inflation_Rate_MoM               805654 non-null   float64
 58  LFPR_rate                        1230968 non-null  float64
 59  Unemployment_Rate                1230968 non-null  float64
dtypes: float64(46), int64(11), object(3)
memory usage: 563.5+ MB