In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
from scipy.stats import shapiro
import sweetviz as sv
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", 1000)
pd.set_option('display.float_format', '{:.3f}'.format)

## Labour Force Survey

#### Data Loading

In [36]:
import os
import pandas as pd

# Set the working directory to the script's location
os.chdir('/Users/joudisinjab/Documents/GitHub/capstone_project')

# Listing all CSV file paths
csv_files = [
    'Data/pub0124.csv',
    'Data/pub0224.csv',
    'Data/pub0324.csv',
    'Data/pub0424.csv',
    'Data/pub0524.csv',
    'Data/pub0624.csv',
    'Data/pub0724.csv',
    'Data/pub0824.csv',
    'Data/pub0924.csv',
    'Data/pub1024.csv',
    'Data/pub1124.csv', 
    'Data/pub1224.csv']

# Load all CSVs into a list of DataFrames
dfs = [pd.read_csv(file) for file in csv_files]

# Concatenate them into one DataFrame
LFS = pd.concat(dfs, ignore_index=True)
print(f"There are {LFS.shape[0]} rows, and {LFS.shape[1]} columns in the LFS dataset")
print(LFS.info())

There are 1343036 rows, and 60 columns in the LFS dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1343036 entries, 0 to 1343035
Data columns (total 60 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   REC_NUM   1343036 non-null  int64
 1   SURVYEAR  1343036 non-null  int64
 2   SURVMNTH  1343036 non-null  int64
 3   LFSSTAT   1343036 non-null  int64
 4   PROV      1343036 non-null  int64
 5   CMA       1343036 non-null  int64
 6   AGE_12    1343036 non-null  int64
 7   AGE_6     266995 non-null   float64
 8   SEX       1343036 non-null  int64
 9   MARSTAT   1343036 non-null  int64
 10  EDUC      1343036 non-null  int64
 11  MJH       789197 non-null   float64
 12  EVERWORK  553839 non-null   float64
 13  FTPTLAST  89401 non-null    float64
 14  COWMAIN   878598 non-null   float64
 15  IMMIG     1343036 non-null  int64
 16  NAICS_21  878598 non-null   float64
 17  NOC_10    878598 non-null   float64
 18  NOC_43    878598 non-null   float64
 19  YABSENT   71835 non-null    float64
 20  WKSAWAY   71835 non-null    float64
 21  PAYAWAY   65118 non-null    float64
 22  UHRSMAIN  789197 non-null   float64
 23  AHRSMAIN  789197 non-null   float64
 24  FTPTMAIN  789197 non-null   float64
 25  UTOTHRS   789197 non-null   float64
 26  ATOTHRS   789197 non-null   float64
 27  HRSAWAY   622568 non-null   float64
 28  YAWAY     99885 non-null    float64
 29  PAIDOT    622568 non-null   float64
 30  UNPAIDOT  622568 non-null   float64
 31  XTRAHRS   622568 non-null   float64
 32  WHYPT     143493 non-null   float64
 33  TENURE    789197 non-null   float64
 34  PREVTEN   89401 non-null    float64
 35  HRLYEARN  683613 non-null   float64
 36  UNION     683613 non-null   float64
 37  PERMTEMP  683613 non-null   float64
 38  ESTSIZE   683613 non-null   float64
 39  FIRMSIZE  683613 non-null   float64
 40  DURUNEMP  49491 non-null    float64
 41  FLOWUNEM  51885 non-null    float64
 42  UNEMFTPT  51885 non-null    float64
 43  WHYLEFTO  89401 non-null    float64
 44  WHYLEFTN  89401 non-null    float64
 45  DURJLESS  463586 non-null   float64
 46  AVAILABL  58349 non-null    float64
 47  LKPUBAG   6827 non-null     float64
 48  LKEMPLOY  25073 non-null    float64
 49  LKRELS    17197 non-null    float64
 50  LKATADS   37659 non-null    float64
 51  LKANSADS  22640 non-null    float64
 52  LKOTHERN  12591 non-null    float64
 53  PRIORACT  47547 non-null    float64
 54  YNOLOOK   16886 non-null    float64
 55  TLOLOOK   1944 non-null     float64
 56  SCHOOLN   999726 non-null   float64
 57  EFAMTYPE  1343036 non-null  int64
 58  AGYOWNK   348535 non-null   float64
 59  FINALWT   1343036 non-null  int64
dtypes: float64(47), int64(13)
memory usage: 614.8 MB
None

In [37]:
print(f"There are {LFS.duplicated().sum()} duplicates in LFS\n")
print("Summary information about LFS dataset:\n")
LFS.describe()

There are 0 duplicates in LFS

Summary information about LFS dataset:

          REC_NUM    SURVYEAR    SURVMNTH     LFSSTAT        PROV         CMA      AGE_12      AGE_6         SEX     MARSTAT        EDUC        MJH   EVERWORK  FTPTLAST    COWMAIN       IMMIG   NAICS_21     NOC_10     NOC_43   YABSENT   WKSAWAY   PAYAWAY   UHRSMAIN   AHRSMAIN   FTPTMAIN    UTOTHRS    ATOTHRS    HRSAWAY     YAWAY     PAIDOT   UNPAIDOT    XTRAHRS      WHYPT     TENURE   PREVTEN   HRLYEARN      UNION   PERMTEMP    ESTSIZE   FIRMSIZE  DURUNEMP  FLOWUNEM  UNEMFTPT  WHYLEFTO  WHYLEFTN   DURJLESS  AVAILABL  LKPUBAG  LKEMPLOY    LKRELS   LKATADS  LKANSADS  LKOTHERN  PRIORACT   YNOLOOK  TLOLOOK    SCHOOLN    EFAMTYPE    AGYOWNK     FINALWT
count 1343036.000 1343036.000 1343036.000 1343036.000 1343036.000 1343036.000 1343036.000 266995.000 1343036.000 1343036.000 1343036.000 789197.000 553839.000 89401.000 878598.000 1343036.000 878598.000 878598.000 878598.000 71835.000 71835.000 65118.000 789197.000 789197.000 789197.000 789197.000 789197.000 622568.000 99885.000 622568.000 622568.000 622568.000 143493.000 789197.000 89401.000 683613.000 683613.000 683613.000 683613.000 683613.000 49491.000 51885.000 51885.000 89401.000 89401.000 463586.000 58349.000 6827.000 25073.000 17197.000 37659.000 22640.000 12591.000 47547.000 16886.000 1944.000 999726.000 1343036.000 348535.000 1343036.000
mean    55966.545    2024.000       6.524       2.252      34.580       1.747       7.221      3.597       1.513       2.877       3.465      1.056      2.002     1.342      2.122       2.703     13.176      5.189     22.850     1.855    12.989     1.513    357.369    320.730      1.182    365.390    327.814     17.005     2.081      8.169      6.107     14.276      4.110     94.012    61.858   3461.084      2.365      1.241      2.208      2.994    17.165     4.502     1.355     3.314     7.567    109.261     1.937    1.000     1.000     1.000     1.000     1.000     1.000     1.584     2.442    1.639      1.145       6.279      2.207     300.364
std     32319.112       0.000       3.443       1.416      14.598       2.788       3.602      1.730       0.500       2.175       1.631      0.231      0.570     0.474      1.190       0.591      5.055      2.653     12.738     1.120    21.174     0.500    116.447    161.302      0.386    122.161    165.934     49.246     1.057     35.928     27.961     45.003      1.822     84.158    81.845   1878.131      0.920      0.710      1.047      1.164    20.618     2.085     0.567     1.450     3.449     88.635     0.242    0.000     0.000     0.000     0.000     0.000     0.000     0.990     1.931    0.480      0.402       5.430      1.084     277.488
min         1.000    2024.000       1.000       1.000      10.000       0.000       1.000      1.000       1.000       1.000       0.000      1.000      1.000     1.000      1.000       1.000      1.000      1.000      1.000     0.000     1.000     1.000      1.000      0.000      1.000      1.000      0.000      0.000     0.000      0.000      0.000      0.000      0.000      1.000     1.000    577.000      1.000      1.000      1.000      1.000     1.000     1.000     1.000     0.000     0.000      1.000     1.000    1.000     1.000     1.000     1.000     1.000     1.000     0.000     0.000    1.000      1.000       1.000      1.000       1.000
25%     27980.000    2024.000       4.000       1.000      24.000       0.000       4.000      2.000       1.000       1.000       2.000      1.000      2.000     1.000      2.000       3.000     10.000      3.000     10.000     1.000     1.000     1.000    325.000    240.000      1.000    350.000    240.000      0.000     1.000      0.000      0.000      0.000      4.000     21.000     5.000   2100.000      1.000      1.000      1.000      2.000     4.000     2.000     1.000     3.000     5.000     24.000     2.000    1.000     1.000     1.000     1.000     1.000     1.000     1.000     1.000    1.000      1.000       2.000      1.000     130.000
50%     55960.000    2024.000       7.000       1.000      35.000       0.000       7.000      4.000       2.000       2.000       4.000      1.000      2.000     1.000      2.000       3.000     14.000      5.000     24.000     2.000     3.000     2.000    400.000    375.000      1.000    400.000    375.000      0.000     2.000      0.000      0.000      0.000      4.000     63.000    19.000   2975.000      3.000      1.000      2.000      4.000     8.000     5.000     1.000     4.000     7.000     90.000     2.000    1.000     1.000     1.000     1.000     1.000     1.000     1.000     2.000    2.000      1.000       4.000      2.000     211.000
75%     83940.000    2024.000      10.000       4.000      47.000       4.000      11.000      5.000       2.000       6.000       5.000      1.000      2.000     2.000      2.000       3.000     17.000      7.000     34.000     3.000    15.000     2.000    400.000    400.000      1.000    400.000    400.000      0.000     3.000      0.000      0.000      0.000      5.000    163.000    84.000   4327.000      3.000      1.000      3.000      4.000    21.000     6.000     2.000     4.000    10.000    198.000     2.000    1.000     1.000     1.000     1.000     1.000     1.000     3.000     4.000    2.000      1.000      11.000      3.000     352.000
max    113108.000    2024.000      12.000       4.000      59.000       9.000      12.000      6.000       2.000       6.000       6.000      2.000      3.000     2.000      7.000       3.000     21.000     10.000     43.000     3.000    99.000     2.000    990.000    990.000      2.000    990.000    990.000    990.000     4.000    990.000    990.000    990.000      7.000    240.000   240.000  23077.000      3.000      4.000      4.000      4.000    99.000     8.000     3.000     5.000    13.000    240.000     2.000    1.000     1.000     1.000     1.000     1.000     1.000     3.000     6.000    2.000      3.000      18.000      4.000    3403.000

#### Data cleaning

In [38]:
### Renaming columns for clarity 
LFS = LFS.rename(columns={'SURVYEAR' : 'survey_year', 'SURVMNTH' : 'survey_month', 'LFSSTAT' : 'lf_status', 'PROV' : 'province', 'CMA' : 'cmetrop_area', 'AGE_12' : '5y_age', 'AGE_6' : '2_3y_age', 
                          'SEX' : 'sex', 'MARSTAT' : 'marital_stat', 'EDUC' : 'education', 'MJH' : 'multiple_jobh', 'EVERWORK' : 'work_lasty', 'FTPTlast' : 'ft_pt_last', 
                          'COWMAIN' : 'main_class_worker', 'IMMIG' : 'immigration_stat', 'YABSENT' : 'rsn_absent_fullwk', 'WKSAWAY' : 'weeks_absent', 'PAYAWAY' : 'paid_for_absence', 
                          'UHRSMAIN': 'usualhrs_main', 'AHRSMAIN' : 'actualhrs_main', 'FTPTMAIN' : 'ft_pt_main', 'UTOTHRS' : 'usualhrs_all', 'ATOTHRS' : 'actualhrs_all',
                          'HRSAWAY' : 'hrs_away', 'YAWAY' : 'rsn_away', 'PAIDOT' : 'paid_overtime', 'UNPAIDOT' : 'unpaid_overtime', 'XTRAHRS' : 'hrs_overtime', 
                          'WHYPT' : 'rsn_pt', 'TENURE' : 'current_tenure', 'PREVTEN' : 'prev_tenure', 'HRLYEARN' : 'hourly_wage', 'UNION' : 'union_stat', 
                          'PERMTEMP' : 'job_permenancy', 'ESTSIZE' : 'estab_size', 'FIRMSIZE' : 'firm_size', 'DURUNEMP' : 'duration_unemp', 
                          'FLOWUNEM' : 'flow_to_unemp', 'UNEMFTPT' : 'job_seekers_temp_layoffs_status', 'WHYLEFTO' : 'rsn_left_old', 
                          'WHYLEFTN' : 'rsn_left_new', 'DURJLESS' : 'duration_jobless', 'AVAILABL' : 'availability', 'LKEMPLOY' : 'unemp_checked_employers',
                          'LKPUBAG' : 'unemp_public_agency', 'LKRELS' : 'unemp_checked_friends', 'LKATADS' : 'unemp_job_ads', 'LKANSADS' : 'unemp_answered_ads',
                          'LKOTHERN' : 'unemp_other_methods', 'PRIORACT' : 'prior_activity', 'YNOLOOK' : 'rsn_not_looking', 'TLOLOOK' : 'temp_layoff_looked', 
                          'SCHOOLN' : 'student_status', 'EFAMTYPE' : 'econ_fam_type', 'AGYOWNK' : 'age_youngest', 'FINALWT' : 'final_wt', 'FTPTLAST' : 'ft_pt_last'})

In [39]:
# Fixing categorical variable types 
ordinal_vars = [
    'lf_status', '5y_age', '2_3y_age', 'education', 'marital_stat', 'work_lasty',
    'job_permenancy', 'estab_size', 'firm_size', 'student_status', 
]

nominal_vars = [
    'survey_month', 'province', 'cmetrop_area', 'sex', 'multiple_jobh', 
     'ft_pt_last', 'main_class_worker', 'immigration_stat', 
    'NAICS_21', 'NOC_10', 'NOC_43', 'rsn_absent_fullwk', 'ft_pt_main', 
    'rsn_away', 'rsn_pt', 'union_stat', 'flow_to_unemp' , 'availability',
    'job_seekers_temp_layoffs_status', 'rsn_left_old', 'rsn_left_new', 
    'prior_activity', 'econ_fam_type', 'paid_for_absence'
]
# Convert ordinal variables
for var in ordinal_vars:
    LFS[var] = pd.Categorical(LFS[var], ordered=True)  

# Convert nominal variables
for var in nominal_vars:
    LFS[var] = LFS[var].astype('category')

# Check the data types
print(LFS.dtypes)

REC_NUM                               int64
survey_year                           int64
survey_month                       category
lf_status                          category
province                           category
cmetrop_area                       category
5y_age                             category
2_3y_age                           category
sex                                category
marital_stat                       category
education                          category
multiple_jobh                      category
work_lasty                         category
ft_pt_last                         category
main_class_worker                  category
immigration_stat                   category
NAICS_21                           category
NOC_10                             category
NOC_43                             category
rsn_absent_fullwk                  category
weeks_absent                        float64
paid_for_absence                   category
usualhrs_main                       float64
actualhrs_main                      float64
ft_pt_main                         category
usualhrs_all                        float64
actualhrs_all                       float64
hrs_away                            float64
rsn_away                           category
paid_overtime                       float64
unpaid_overtime                     float64
hrs_overtime                        float64
rsn_pt                             category
current_tenure                      float64
prev_tenure                         float64
hourly_wage                         float64
union_stat                         category
job_permenancy                     category
estab_size                         category
firm_size                          category
duration_unemp                      float64
flow_to_unemp                      category
job_seekers_temp_layoffs_status    category
rsn_left_old                       category
rsn_left_new                       category
duration_jobless                    float64
availability                       category
unemp_public_agency                 float64
unemp_checked_employers             float64
unemp_checked_friends               float64
unemp_job_ads                       float64
unemp_answered_ads                  float64
unemp_other_methods                 float64
prior_activity                     category
rsn_not_looking                     float64
temp_layoff_looked                  float64
student_status                     category
econ_fam_type                      category
age_youngest                        float64
final_wt                              int64
dtype: object

In [40]:
## Formatting column data types
LFS['REF_DATE'] = LFS['survey_year'].astype(str) + "-" + LFS['survey_month'].astype(str).str.zfill(2)
LFS['REF_DATE'] = pd.to_datetime(LFS['REF_DATE'], format='%Y-%m')
LFS['month'] = LFS['REF_DATE'].dt.strftime('%b')

month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Convert the 'month' column to a categorical type with the specified order for easier visualization
LFS['month'] = pd.Categorical(LFS['month'], categories=month_order, ordered=True)

LFS = LFS.sort_values('month')

## Data documentation states that two decimal spaces are implied, changing the format to show true hourly wage
LFS['hourly_wage'] = LFS['hourly_wage']/100

## Data documentation states that one decimal space is implied
LFS['usualhrs_main'] = LFS['usualhrs_main'] / 10
LFS['actualhrs_main'] = LFS['actualhrs_main'] / 10
LFS['usualhrs_all'] = LFS['usualhrs_all'] / 10
LFS['actualhrs_all'] = LFS['actualhrs_all'] / 10
LFS['hrs_away'] = LFS['hrs_away'] / 10
LFS['paid_overtime'] = LFS['paid_overtime'] / 10
LFS['unpaid_overtime'] = LFS['unpaid_overtime'] / 10
LFS['hrs_overtime'] = LFS['hrs_overtime'] / 10

In [41]:
## Dropping highly null columns and unrelevant columns to analysis
col_to_drop = ['age_youngest', 'unemp_public_agency', 'unemp_checked_employers', 'unemp_checked_friends', 'unemp_job_ads', 'unemp_answered_ads', 
                'unemp_other_methods', 'rsn_not_looking', 'temp_layoff_looked', 'survey_year']

for col in col_to_drop:
    LFS.drop(columns=[col], inplace=True)
    print(f"{col} has been dropped from LFS dataframe due to a high percentage of missing values.")

age_youngest has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_public_agency has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_checked_employers has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_checked_friends has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_job_ads has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_answered_ads has been dropped from LFS dataframe due to a high percentage of missing values.
unemp_other_methods has been dropped from LFS dataframe due to a high percentage of missing values.
rsn_not_looking has been dropped from LFS dataframe due to a high percentage of missing values.
temp_layoff_looked has been dropped from LFS dataframe due to a high percentage of missing values.
survey_year has been dropped from LFS dataframe due to a high percentage of missing values.

In [42]:
LFS.to_csv('Data/LFS.csv', index=False)

## Job Vacancies

#### Data Loading

In [43]:
JV = pd.read_csv('Data/Job vacancies, payroll employees, and job vacancy rate by industry sector, monthly, adjusted for seasonality.csv')

JV_wide = JV.pivot(index=["REF_DATE", "North American Industry Classification System (NAICS)"], 
                   columns=["Statistics"], values="VALUE").reset_index()

print(f"There are {JV_wide.shape[0]} rows, and {JV_wide.shape[1]} columns in the JV dataset")

JV_wide.head()

There are 252 rows, and 5 columns in the JV dataset

Statistics REF_DATE North American Industry Classification System (NAICS)  Job vacancies  Job vacancy rate  Payroll employees
0           2024-01               Accommodation and food services [72]         82045.000             5.900        1296970.000
1           2024-01  Administrative and support, waste management a...         37060.000             4.300         834015.000
2           2024-01    Agriculture, forestry, fishing and hunting [11]          8740.000             3.500         239455.000
3           2024-01            Arts, entertainment and recreation [71]         12025.000             3.700         314880.000
4           2024-01                                  Construction [23]         52785.000             4.300        1171530.000

In [44]:
print("Summary information about JV dataset:\n")
print(JV_wide.info()) 

print("\nSummary statistics about JV dataset:\n")
JV_wide.describe()

Summary information about JV dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 5 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   REF_DATE                                               252 non-null    object
 1   North American Industry Classification System (NAICS)  252 non-null    object
 2   Job vacancies                                          250 non-null    float64
 3   Job vacancy rate                                       250 non-null    float64
 4   Payroll employees                                      252 non-null    float64
dtypes: float64(3), object(2)
memory usage: 10.0+ KB
None

Summary statistics about JV dataset:

Statistics  Job vacancies  Job vacancy rate  Payroll employees
count             250.000           250.000            252.000
mean            54509.940             2.945        1644529.663
std            119241.555             0.984        3553314.801
min              1665.000             1.200         118005.000
25%              8450.000             2.300         314970.000
50%             22997.500             2.700         825222.500
75%             40008.750             3.575        1307413.750
max            662905.000             5.900       17317010.000

#### Data Cleaning

In [45]:
JV_wide['REF_DATE'] = pd.to_datetime(JV_wide['REF_DATE'], format='%Y-%m')

In [46]:
# Renaming columns for clarity 
JV_wide = JV_wide.rename(columns={"North American Industry Classification System (NAICS)": "NAICS_21", "Job vacancies": "Job Vacancies (#)",
                                 "Job vacancy rate": "Job Vacancy Rate (%)", "Payroll employees": "Payroll Employees (#)"})

#Checking for missing values
print(f"There is {JV_wide.isnull().sum()} missing values in JV dataset:\n")
JV_wide[JV_wide.isnull().any(axis=1)]

There is Statistics
REF_DATE                 0
NAICS_21                 0
Job Vacancies (#)        2
Job Vacancy Rate (%)     2
Payroll Employees (#)    0
dtype: int64 missing values in JV dataset:

Statistics   REF_DATE                                  NAICS_21  Job Vacancies (#)  Job Vacancy Rate (%)  Payroll Employees (#)
124        2024-06-01                            Utilities [22]                NaN                   NaN             135020.000
218        2024-11-01  Information and cultural industries [51]                NaN                   NaN             355840.000

Checking for normality before imputing missing values with the mean

In [47]:
industries_of_interest = ['Utilities [22]', 'Information and cultural industries [51]']

for industry in industries_of_interest:
    industry_data = JV_wide[JV_wide["NAICS_21"] == industry]
    
    # Shapiro test for Job Vacancies
    job_vacancies = industry_data["Job Vacancies (#)"].dropna()
    stat_vacancies, p_vacancies = shapiro(job_vacancies)

    # Shapiro test for Job Vacancy Rate
    job_vacancy_rate = industry_data["Job Vacancy Rate (%)"].dropna()
    stat_rate, p_rate = shapiro(job_vacancy_rate)
    
    print(f"\nShapiro-Wilk Test for {industry}:")
    print(f"Job Vacancies (#): W-statistic={stat_vacancies:.4f}, p-value={p_vacancies:.4f}")
    if p_vacancies > 0.05:
        print("Job Vacancies data is normally distributed\n")
    else:
        print("Job Vacancies data is not normally distributed\n")

    print(f"Job Vacancy Rate (%): W-statistic={stat_rate:.4f}, p-value={p_rate:.4f}")
    if p_rate > 0.05:
        print("Job Vacancy Rate data is normally distributed\n")
    else:
        print("Job Vacancy Rate data is not normally distributed\n")

Shapiro-Wilk Test for Utilities [22]:
Job Vacancies (#): W-statistic=0.9498, p-value=0.6418
Job Vacancies data is normally distributed

Job Vacancy Rate (%): W-statistic=0.9424, p-value=0.5488
Job Vacancy Rate data is normally distributed


Shapiro-Wilk Test for Information and cultural industries [51]:
Job Vacancies (#): W-statistic=0.8666, p-value=0.0701
Job Vacancies data is normally distributed

Job Vacancy Rate (%): W-statistic=0.8640, p-value=0.0648
Job Vacancy Rate data is normally distributed

In [48]:
# Since the distributions of both industries is normal, missing values will be imputed with industry mean for each statistic 

# Calculate the mean for each industry
mean_values = JV_wide.groupby("NAICS_21")[["Job Vacancies (#)", "Job Vacancy Rate (%)"]].transform("mean")

# Fill missing values with the mean
JV_wide.fillna(mean_values, inplace=True)

In [67]:
# Combining industries to match LFS Mapping because of inability to accurately split groups in JV, limitation in study
industry_mapping = {
    'Management of companies and enterprises [55]': 'Business, building and other support services [55-56]',
    'Administrative and support, waste management and remediation services [56]': 'Business, building and other support services [55-56]',
    'Information and cultural industries [51]': 'Information, culture and recreation [51-71]',
    'Arts, entertainment and recreation [71]': 'Information, culture and recreation [51-71]'
}

# Apply mapping to create a new industry column
JV_wide['combined_industries'] = JV_wide['NAICS_21'].replace(industry_mapping)

# Ensure unmapped industries stay the same
JV_wide['combined_industries'] = JV_wide['combined_industries'].fillna(JV_wide['NAICS_21'])

# Aggregating data
JV_aggregated = JV_wide.groupby(['REF_DATE', 'combined_industries']).agg({
    'Job Vacancies (#)': 'sum',  
    'Payroll Employees (#)': 'sum',  
    'Job Vacancy Rate (%)': lambda x: (x * JV_wide.loc[x.index, 'Payroll Employees (#)']).sum() / 
                                             JV_wide.loc[x.index, 'Payroll Employees (#)'].sum()
}).reset_index()

# Dropping rows in which statistics calculated are for all industries combined
# JV_aggregated.drop(JV_aggregated[JV_aggregated['combined_industries'] == 'Total, all industries'].index, inplace=True)


JV_aggregated.head()

Statistics   REF_DATE                                combined_industries  Job Vacancies (#)  Payroll Employees (#)  Job Vacancy Rate (%)
0          2024-01-01               Accommodation and food services [72]          82045.000            1296970.000                 5.900
1          2024-01-01    Agriculture, forestry, fishing and hunting [11]           8740.000             239455.000                 3.500
2          2024-01-01  Business, building and other support services ...          39610.000             955710.000                 4.020
3          2024-01-01                                  Construction [23]          52785.000            1171530.000                 4.300
4          2024-01-01                          Educational services [61]          22275.000            1440025.000                 1.500

In [50]:
JV_aggregated.to_csv('Data/JV_aggregated.csv', index=False)

## Consumer Price Index

#### Data Loading

In [51]:
CPI = pd.read_csv('Data/Consumer Price Index, monthly, seasonally adjusted1.csv')

CPI_pivot = CPI.pivot(index="REF_DATE", columns="Products and product groups", values="VALUE").reset_index()

print(f"There are {CPI_pivot.shape[0]} rows, and {CPI_pivot.shape[1]} columns in the CPI dataset")

CPI_pivot.head()

There are 13 rows, and 12 columns in the CPI dataset

Products and product groups REF_DATE  Alcoholic beverages, tobacco products and recreational cannabis  All-items  All-items excluding food  All-items excluding food and energy  Clothing and footwear    Food  Health and personal care  Household operations, furnishings and equipment  Recreation, education and reading  Shelter  Transportation
0                            2023-12                                            193.600                  159.500                   154.400                              149.500                 97.000 187.500                   147.600                                          130.900                            126.700  177.800         172.300
1                            2024-01                                            194.200                  159.300                   154.200                              149.600                 95.300 187.500                   148.300                                          131.400                            125.900  178.400         170.900
2                            2024-02                                            194.200                  159.500                   154.400                              149.800                 93.100 187.400                   148.900                                          130.800                            126.600  179.200         171.500
3                            2024-03                                            194.700                  159.900                   154.800                              150.100                 94.400 187.400                   149.000                                          130.100                            127.200  179.900         172.200
4                            2024-04                                            195.500                  160.200                   155.200                              150.400                 94.200 187.300                   149.400                                          130.400                            127.200  180.800         172.800

In [52]:
print("Summary information about CPI dataset:\n")
print(CPI_pivot.info())

print("Summary information about CPI dataset:\n")
CPI_pivot.describe()

Summary information about CPI dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   REF_DATE                                                         13 non-null     object
 1   Alcoholic beverages, tobacco products and recreational cannabis  13 non-null     float64
 2   All-items                                                        13 non-null     float64
 3   All-items excluding food                                         13 non-null     float64
 4   All-items excluding food and energy                              13 non-null     float64
 5   Clothing and footwear                                            13 non-null     float64
 6   Food                                                             13 non-null     float64
 7   Health and personal care                                         13 non-null     float64
 8   Household operations, furnishings and equipment                  13 non-null     float64
 9   Recreation, education and reading                                13 non-null     float64
 10  Shelter                                                          13 non-null     float64
 11  Transportation                                                   13 non-null     float64
dtypes: float64(11), object(1)
memory usage: 1.3+ KB
None
Summary information about CPI dataset:

Products and product groups  Alcoholic beverages, tobacco products and recreational cannabis  All-items  All-items excluding food  All-items excluding food and energy  Clothing and footwear    Food  Health and personal care  Household operations, furnishings and equipment  Recreation, education and reading  Shelter  Transportation
count                                                                   13.000                   13.000                    13.000                               13.000                 13.000  13.000                    13.000                                           13.000                             13.000   13.000          13.000
mean                                                                   195.977                  160.754                   155.577                              151.023                 93.669 189.138                   150.200                                          130.700                            127.031  181.915         171.908
std                                                                      1.667                    1.019                     0.973                                1.069                  1.329   1.727                     1.463                                            0.471                              0.720    2.611           1.266
min                                                                    193.600                  159.300                   154.200                              149.500                 92.400 187.300                   147.600                                          129.900                            125.900  177.800         170.000
25%                                                                    194.700                  159.900                   154.800                              150.100                 92.700 187.500                   149.000                                          130.400                            126.700  179.900         170.900
50%                                                                    195.800                  160.800                   155.600                              151.200                 93.600 188.600                   150.400                                          130.800                            126.800  182.100         171.900
75%                                                                    197.500                  161.300                   156.000                              151.800                 94.200 190.500                   151.500                                          130.900                            127.200  183.500         172.300
max                                                                    198.500                  162.400                   157.500                              152.700                 97.000 191.900                   152.300                                          131.500                            128.700  185.800         175.100

#### Data Cleaning

In [53]:
CPI_pivot["REF_DATE"] = pd.to_datetime(CPI_pivot["REF_DATE"], format='%Y-%m')

Extracting All items CPI

In [68]:
CPI_all_items = CPI_pivot[['REF_DATE', "All-items"]]

CPI_all_items = CPI_all_items.sort_values(by="REF_DATE")

CPI_all_items["Inflation_Rate_MoM"] = CPI_all_items["All-items"].pct_change() * 100  # Converts to percentage

CPI_all_items.dropna(inplace=True)

CPI_all_items

Products and product groups   REF_DATE  All-items  Inflation_Rate_MoM
1                           2024-01-01    159.300              -0.125
2                           2024-02-01    159.500               0.126
3                           2024-03-01    159.900               0.251
4                           2024-04-01    160.200               0.188
5                           2024-05-01    160.600               0.250
6                           2024-06-01    160.800               0.125
7                           2024-07-01    161.200               0.249
8                           2024-08-01    161.300               0.062
9                           2024-09-01    161.300               0.000
10                          2024-10-01    161.800               0.310
11                          2024-11-01    162.000               0.124
12                          2024-12-01    162.400               0.247

In [55]:
CPI_all_items.to_csv('Data/CPI_all_items.csv', index=False)

## Preprocessing

Feature engineering labour force participation rate, unemployment rate, employment rate, and market tightness and merging with 'Total, All industries' Job vacancy data

In [73]:
weight_col = 'final_wt'
# Define employment categories
employed = LFS[LFS['lf_status'].isin([1, 2])]
unemployed = LFS[LFS['lf_status'] == 3]
labour_force = LFS[LFS['lf_status'].isin([1, 2, 3])]
employed_clean = employed[(employed['hourly_wage'] != 0) & (~employed['hourly_wage'].isna())]

# Group by REF_DATE (monthly) and sum weights
monthly_employed = employed.groupby('REF_DATE')[weight_col].sum()
monthly_unemployed = unemployed.groupby('REF_DATE')[weight_col].sum()
monthly_labour_force = labour_force.groupby('REF_DATE')[weight_col].sum()
monthly_working_age_pop = LFS.groupby('REF_DATE')[weight_col].sum()
weighted_hourly_wage_sum = employed_clean.groupby('REF_DATE').apply(lambda x: (x['hourly_wage'] * x[weight_col]).sum())
total_weight = employed_clean.groupby('REF_DATE')[weight_col].sum()

# Calculate Average Hourly Wage before merging
average_hourly_wage = weighted_hourly_wage_sum / total_weight

# Calculate Monthly Employment & Unemployment Rates
employment_rate = (monthly_employed / monthly_working_age_pop) * 100
unemployment_rate = (monthly_unemployed / monthly_labour_force) * 100
participation_rate = (monthly_labour_force / monthly_working_age_pop) * 100

# Combine into a DataFrame
monthly_rates = pd.DataFrame({
    'Employment Rate (%)': employment_rate,
    'Unemployment Rate (%)': unemployment_rate, 
    'Labour Force Participation Rate (%)': participation_rate,
    'Unemployed': monthly_unemployed,
    'Average Hourly Wage': average_hourly_wage
}).reset_index()

# Merging with JV & CPI data 
total_industries = JV_aggregated[JV_aggregated['combined_industries'] == 'Total, all industries']
monthly_rates = monthly_rates.merge(total_industries, on= 'REF_DATE', how='left')
monthly_rates = monthly_rates.merge(CPI_all_items, on= 'REF_DATE', how='left')

# Calculating Market Tightness 
monthly_rates["Market_Tightness"] = monthly_rates["Job Vacancies (#)"] / monthly_rates["Unemployed"]

monthly_rates

# Calculate Monthly Employment & Unemployment Rates
employment_rate = (monthly_employed / monthly_working_age_pop) * 100
unemployment_rate = (monthly_unemployed / monthly_labour_force) * 100
participation_rate = (monthly_labour_force / monthly_working_age_pop) * 100

# Combine into a DataFrame
monthly_rates = pd.DataFrame({
    'Employment Rate (%)': employment_rate,
    'Unemployment Rate (%)': unemployment_rate, 
    'Labour Force Participation Rate (%)': participation_rate,
    'Unemployed': monthly_unemployed,
    'Average Hourly Wage': average_hourly_wage
}).reset_index()

# Merging with JV & CPI data 
total_industries = JV_aggregated[JV_aggregated['combined_industries'] == 'Total, all industries']
monthly_rates = monthly_rates.merge(total_industries, on= 'REF_DATE', how='left')
monthly_rates = monthly_rates.merge(CPI_all_items, on= 'REF_DATE', how='left')

# Calculating Market Tightness 
monthly_rates["Market_Tightness"] = monthly_rates["Job Vacancies (#)"] / monthly_rates["Unemployed"]

monthly_rates

/var/folders/n9/29yl9jnj61q74vg3ydjdf3qh0000gn/T/ipykernel_7135/1857826084.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weighted_hourly_wage_sum = employed_clean.groupby('REF_DATE').apply(lambda x: (x['hourly_wage'] * x[weight_col]).sum())

     REF_DATE  Employment Rate (%)  Unemployment Rate (%)  Labour Force Participation Rate (%)  Unemployed  Average Hourly Wage    combined_industries  Job Vacancies (#)  Payroll Employees (#)  Job Vacancy Rate (%)  All-items  Inflation_Rate_MoM  Market_Tightness
0  2024-01-01               60.585                  6.141                               64.549     1311310               34.749  Total, all industries         662905.000           17182760.000                 3.700    159.300              -0.125             0.506
1  2024-02-01               60.780                  6.046                               64.691     1297139               34.820  Total, all industries         659070.000           17235150.000                 3.700    159.500               0.126             0.508
2  2024-03-01               60.732                  6.442                               64.914     1390601               34.811  Total, all industries         602470.000           17241295.000                 3.400    159.900               0.251             0.433
3  2024-04-01               61.064                  6.227                               65.119     1352940               34.947  Total, all industries         592915.000           17266410.000                 3.300    160.200               0.188             0.438
4  2024-05-01               61.917                  6.291                               66.074     1390949               34.939  Total, all industries         571315.000           17269645.000                 3.200    160.600               0.250             0.411
5  2024-06-01               62.112                  6.173                               66.199     1371396               34.906  Total, all industries         552890.000           17316575.000                 3.100    160.800               0.125             0.403
6  2024-07-01               61.498                  6.756                               65.954     1501057               34.971  Total, all industries         545695.000           17257555.000                 3.100    161.200               0.249             0.364
7  2024-08-01               61.250                  7.476                               66.199     1671938               35.160  Total, all industries         529300.000           17273205.000                 3.000    161.300               0.062             0.317
8  2024-09-01               60.920                  6.018                               64.820     1322025               35.591  Total, all industries         528720.000           17317010.000                 3.000    161.300               0.000             0.400
9  2024-10-01               60.858                  5.941                               64.702     1306127               35.764  Total, all industries         515655.000           17268810.000                 2.900    161.800               0.310             0.395
10 2024-11-01               60.654                  6.487                               64.862     1432989               35.682  Total, all industries         520635.000           17301165.000                 2.900    162.000               0.124             0.363
11 2024-12-01               60.577                  6.175                               64.564     1360544               35.774  Total, all industries         536095.000           17281145.000                 3.000    162.400               0.247             0.394

In [74]:
monthly_rates.to_csv('Monthly Labour Market Rates.csv')

Feature engineering labour force participation rate, unemployment rate, employment rate, and market tightness by industry and merging with Job vacancy data

In [ ]:
# Grouping Employed (LF_STATUS: 1, 2) by month & industry
employed_by_month_industry = (
    LFS[LFS['lf_status'].isin([1, 2])]
    .groupby(['REF_DATE', 'NAICS_21'])[weight_col]
    .sum()
    .reset_index()
    .rename(columns={weight_col: 'total_employed'})
)

# Grouping Unemployed (LF_STATUS: 3) by month & industry
unemployed_by_month_industry = (
    LFS[LFS['lf_status'] == 3]
    .groupby(['REF_DATE', 'NAICS_21'])[weight_col]
    .sum()
    .reset_index()
    .rename(columns={weight_col: 'total_unemployed'})
)

# Merging employed & unemployed data
monthly_industry_rates = pd.merge(employed_by_month_industry, unemployed_by_month_industry, 
                                  on=['REF_DATE', 'NAICS_21'], how='outer')
monthly_industry_rates

# Labour Force per Industry per Month (Employed + Unemployed)
monthly_industry_rates['labour_force'] = (
    monthly_industry_rates['total_employed'] + monthly_industry_rates['total_unemployed']
)

# Calculating Monthly Employment & Unemployment Rates
monthly_industry_rates['employment_rate'] = (
    (monthly_industry_rates['total_employed'] / monthly_industry_rates['labour_force']) * 100
).round(2)

monthly_industry_rates['unemployment_rate'] = (
    (monthly_industry_rates['total_unemployed'] / monthly_industry_rates['labour_force']) * 100
).round(2)


monthly_industry_rates

/var/folders/n9/29yl9jnj61q74vg3ydjdf3qh0000gn/T/ipykernel_7135/2851284345.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['REF_DATE', 'NAICS_21'])[weight_col]
/var/folders/n9/29yl9jnj61q74vg3ydjdf3qh0000gn/T/ipykernel_7135/2851284345.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['REF_DATE', 'NAICS_21'])[weight_col]

      REF_DATE NAICS_21  total_employed  total_unemployed  labour_force  employment_rate  unemployment_rate
0   2024-01-01    1.000          213422              9264        222686           95.840              4.160
1   2024-01-01    2.000           38504              5537         44041           87.430             12.570
2   2024-01-01    3.000           12747              7904         20651           61.730             38.270
3   2024-01-01    4.000          274051             20097        294148           93.170              6.830
4   2024-01-01    5.000          151786              2299        154085           98.510              1.490
..         ...      ...             ...               ...           ...              ...                ...
247 2024-12-01   17.000         2850404             41674       2892078           98.560              1.440
248 2024-12-01   18.000          813125             66468        879593           92.440              7.560
249 2024-12-01   19.000         1166479             72232       1238711           94.170              5.830
250 2024-12-01   20.000          776049             31094        807143           96.150              3.850
251 2024-12-01   21.000         1195910             20494       1216404           98.320              1.680

[252 rows x 7 columns]

In [59]:
## Mapping JV industries to numerical categories

JV_aggregated.drop(JV_aggregated[JV_aggregated['combined_industries'] == 'Total, all industries'].index, inplace=True)

industry_encoding = {
    'Accommodation and food services [72]': 1, 
    'Business, building and other support services [55-56]': 2, 
    'Agriculture, forestry, fishing and hunting [11]': 3, 
    'Construction [23]': 4,
    'Educational services [61]': 5, 
    'Finance and insurance [52]': 6,
    'Health care and social assistance [62]': 7,
    'Information, culture and recreation [51-71]': 8, 
    'Manufacturing [31-33]': 9, 
    'Mining, quarrying, and oil and gas extraction [21]': 10, 
    'Other services (except public administration) [81]': 11,
    'Professional, scientific and technical services [54]': 12,
    'Public administration [91]': 13,
    'Real estate and rental and leasing [53]': 14,
    'Retail trade [44-45]': 15,
    'Transportation and warehousing [48-49]': 16,
    'Utilities [22]': 17,
    'Wholesale trade [41]': 18
}

JV_aggregated['JV_industry'] = JV_aggregated['combined_industries'].map(industry_encoding)

if JV_aggregated['JV_industry'].isnull().any():
    print("Warning: Some industries could not be mapped. Check for missing values.")

# Mapping categories in LFS to JV

LFS_to_JV = {
    1 : 3,
    2 : 3,  
    3 : 3,  
    4 : 10,
    5 : 17,
    6 : 4,
    7 : 9,  
    8 : 9,  
    9 : 18,
    10: 15,
    11: 16,
    12: 6,
    13: 14,
    14: 12,
    15: 2,  
    16: 5,
    17: 7,
    18: 8,  
    19: 1,
    20: 11,
    21: 13,
}

monthly_industry_rates['NAICS_21_JV'] = monthly_industry_rates['NAICS_21'].map(LFS_to_JV)

if monthly_industry_rates['NAICS_21_JV'].isnull().any():
    print("Warning: Some industries could not be mapped. Check for missing values.")

# Merging JV & CPI with industry monthly rates 
monthly_industry_rates = monthly_industry_rates.merge(JV_aggregated, left_on=["REF_DATE", "NAICS_21_JV"], right_on=["REF_DATE", "JV_industry"], how="left")
monthly_industry_rates = monthly_industry_rates.merge(CPI_all_items, on= 'REF_DATE', how='left') 
monthly_industry_rates

      REF_DATE NAICS_21  total_employed  total_unemployed  labour_force  employment_rate  unemployment_rate  NAICS_21_JV                                combined_industries  Job Vacancies (#)  Payroll Employees (#)  Job Vacancy Rate (%)  JV_industry  All-items  Inflation_Rate_MoM
0   2024-01-01    1.000          213422              9264        222686           95.840              4.160            3    Agriculture, forestry, fishing and hunting [11]           8740.000             239455.000                 3.500            3    159.300              -0.125
1   2024-01-01    2.000           38504              5537         44041           87.430             12.570            3    Agriculture, forestry, fishing and hunting [11]           8740.000             239455.000                 3.500            3    159.300              -0.125
2   2024-01-01    3.000           12747              7904         20651           61.730             38.270            3    Agriculture, forestry, fishing and hunting [11]           8740.000             239455.000                 3.500            3    159.300              -0.125
3   2024-01-01    4.000          274051             20097        294148           93.170              6.830           10  Mining, quarrying, and oil and gas extraction ...           5650.000             208720.000                 2.600           10    159.300              -0.125
4   2024-01-01    5.000          151786              2299        154085           98.510              1.490           17                                     Utilities [22]           3075.000             134150.000                 2.200           17    159.300              -0.125
..         ...      ...             ...               ...           ...              ...                ...          ...                                                ...                ...                    ...                   ...          ...        ...                 ...
247 2024-12-01   17.000         2850404             41674       2892078           98.560              1.440            7             Health care and social assistance [62]         107290.000            2420560.000                 4.200            7    162.400               0.247
248 2024-12-01   18.000          813125             66468        879593           92.440              7.560            8        Information, culture and recreation [51-71]          16305.000             678580.000                 2.342            8    162.400               0.247
249 2024-12-01   19.000         1166479             72232       1238711           94.170              5.830            1               Accommodation and food services [72]          61490.000            1297490.000                 4.500            1    162.400               0.247
250 2024-12-01   20.000          776049             31094        807143           96.150              3.850           11  Other services (except public administration) ...          25275.000             569490.000                 4.200           11    162.400               0.247
251 2024-12-01   21.000         1195910             20494       1216404           98.320              1.680           13                         Public administration [91]          13555.000             577470.000                 2.300           13    162.400               0.247

[252 rows x 15 columns]

Agriculture, forestry, fishing and hunting [11] and Manufacturing [31-33] are each one industry in JV. However, in LFS the Manufacturing [31-33] is divided into 2 sub-industries and Agriculture, forestry, fishing and hunting [11] is divided into 3 sub-industries. The job vacancy data needs to be proportional to each industry.

In [60]:
adjusted_rates = monthly_industry_rates[monthly_industry_rates['NAICS_21'].isin([1,2,3,7,8])]

# Compute total labour force for each JV industry
total_labour_force_per_JV = (
    adjusted_rates.groupby(['REF_DATE', 'NAICS_21_JV'])['labour_force']
    .sum()
    .reset_index()
    .rename(columns={'labour_force': 'total_labour_force_JV'})
)

# Merge total labour force back into adjusted_rates
adjusted_rates = adjusted_rates.merge(total_labour_force_per_JV, on=['REF_DATE', 'NAICS_21_JV'], how='left')

# Compute each subindustry’s labour force proportion within the JV industry
adjusted_rates['labour_force_proportion'] = adjusted_rates['labour_force'] / adjusted_rates['total_labour_force_JV']

# Adjust Job Vacancies and Payroll Employees based on labour force proportion
adjusted_rates['Adjusted Job Vacancies'] = (
    adjusted_rates['Job Vacancies (#)'] * adjusted_rates['labour_force_proportion']
).round(0)  

adjusted_rates['Adjusted Payroll Employees'] = (
    adjusted_rates['Payroll Employees (#)'] * adjusted_rates['labour_force_proportion']
).round(0)  


adjusted_rates.drop(columns=['Job Vacancies (#)', 'Payroll Employees (#)'], inplace=True) 
adjusted_rates.rename(columns={'Adjusted Job Vacancies': 'Job Vacancies (#)', 'Adjusted Payroll Employees': 'Payroll Employees (#)'}, inplace=True)

# Industries that need to be updated
industries_to_update = [1, 2, 3, 7, 8]  # Agriculture & Manufacturing NAICS_21

# Filter out these industries from monthly industry rates dataset
monthly_industry_rates = monthly_industry_rates[~monthly_industry_rates['NAICS_21'].isin(industries_to_update)]

# Append the adjusted data back into the monthly industry rates dataset
updated_monthly_industry_rates = pd.concat([monthly_industry_rates, adjusted_rates], ignore_index=True)

# Ensure data is sorted correctly 
updated_monthly_industry_rates = updated_monthly_industry_rates.sort_values(by=['REF_DATE', 'NAICS_21']).reset_index(drop=True)

# Calculate Market Tightness 
updated_monthly_industry_rates["Market_Tightness"] = updated_monthly_industry_rates["Job Vacancies (#)"] / updated_monthly_industry_rates["total_unemployed"]

# Dropping redundant columns
updated_monthly_industry_rates.drop(columns=['total_employed', 'total_unemployed', 'total_labour_force_JV', 'labour_force_proportion', 
                                            'JV_industry', 'combined_industries', 'NAICS_21_JV', 'labour_force'], inplace=True)
updated_monthly_industry_rates

      REF_DATE NAICS_21  employment_rate  unemployment_rate  Job Vacancies (#)  Payroll Employees (#)  Job Vacancy Rate (%)  All-items  Inflation_Rate_MoM  Market_Tightness
0   2024-01-01    1.000           95.840              4.160           6773.000             185551.000                 3.500    159.300              -0.125             0.731
1   2024-01-01    2.000           87.430             12.570           1339.000              36697.000                 3.500    159.300              -0.125             0.242
2   2024-01-01    3.000           61.730             38.270            628.000              17207.000                 3.500    159.300              -0.125             0.079
3   2024-01-01    4.000           93.170              6.830           5650.000             208720.000                 2.600    159.300              -0.125             0.281
4   2024-01-01    5.000           98.510              1.490           3075.000             134150.000                 2.200    159.300              -0.125             1.338
..         ...      ...              ...                ...                ...                    ...                   ...        ...                 ...               ...
247 2024-12-01   17.000           98.560              1.440         107290.000            2420560.000                 4.200    162.400               0.247             2.575
248 2024-12-01   18.000           92.440              7.560          16305.000             678580.000                 2.342    162.400               0.247             0.245
249 2024-12-01   19.000           94.170              5.830          61490.000            1297490.000                 4.500    162.400               0.247             0.851
250 2024-12-01   20.000           96.150              3.850          25275.000             569490.000                 4.200    162.400               0.247             0.813
251 2024-12-01   21.000           98.320              1.680          13555.000             577470.000                 2.300    162.400               0.247             0.661

[252 rows x 10 columns]

In [70]:
# Calculate average hourly wage per industry and merge with updated_monthly_industry_rates
average_hourly_wage_per_industry = employed_clean.groupby(['REF_DATE', 'NAICS_21'])['hourly_wage'].mean().reset_index()
updated_monthly_industry_rates = updated_monthly_industry_rates.merge(average_hourly_wage_per_industry, on=['REF_DATE', 'NAICS_21'], how='left')
updated_monthly_industry_rates.rename(columns={'hourly_wage': 'Average Hourly Wage'}, inplace=True)
updated_monthly_industry_rates

/var/folders/n9/29yl9jnj61q74vg3ydjdf3qh0000gn/T/ipykernel_7135/3777208408.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_hourly_wage_per_industry = employed_clean.groupby(['REF_DATE', 'NAICS_21'])['hourly_wage'].mean().reset_index()

      REF_DATE NAICS_21  employment_rate  unemployment_rate  Job Vacancies (#)  Payroll Employees (#)  Job Vacancy Rate (%)  All-items  Inflation_Rate_MoM  Market_Tightness  Average Hourly Wage
0   2024-01-01    1.000           95.840              4.160           6773.000             185551.000                 3.500    159.300              -0.125             0.731               23.722
1   2024-01-01    2.000           87.430             12.570           1339.000              36697.000                 3.500    159.300              -0.125             0.242               34.019
2   2024-01-01    3.000           61.730             38.270            628.000              17207.000                 3.500    159.300              -0.125             0.079               30.671
3   2024-01-01    4.000           93.170              6.830           5650.000             208720.000                 2.600    159.300              -0.125             0.281               49.631
4   2024-01-01    5.000           98.510              1.490           3075.000             134150.000                 2.200    159.300              -0.125             1.338               50.538
..         ...      ...              ...                ...                ...                    ...                   ...        ...                 ...               ...                  ...
247 2024-12-01   17.000           98.560              1.440         107290.000            2420560.000                 4.200    162.400               0.247             2.575               33.996
248 2024-12-01   18.000           92.440              7.560          16305.000             678580.000                 2.342    162.400               0.247             0.245               32.138
249 2024-12-01   19.000           94.170              5.830          61490.000            1297490.000                 4.500    162.400               0.247             0.851               20.356
250 2024-12-01   20.000           96.150              3.850          25275.000             569490.000                 4.200    162.400               0.247             0.813               30.942
251 2024-12-01   21.000           98.320              1.680          13555.000             577470.000                 2.300    162.400               0.247             0.661               44.752

[252 rows x 11 columns]

In [71]:
updated_monthly_industry_rates.to_csv('Monthly Industry Labour Market Rates.csv')

## Exploratory Data Analysis

In [ ]:
# LFS_report = sv.analyze(LFS)
# LFS_report.show_html('LFS_EDA_Report.html')

JV_report = sv.analyze(JV_aggregated)
JV_report.show_html('LFS_EDA_Report.html')

CPI_report = sv.analyze(CPI)
CPI_report.show_html('LFS_EDA_Report.html')

monthly_rates_report = sv.analyze(monthly_rates)
monthly_rates_report.show_html('LFS_EDA_Report.html')

industry_rates_report = sv.analyze(updated_monthly_industry_rates)
industry_rates_report.show_html('LFS_EDA_Report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

                                             |          | [  0%]   00:00 -> (? left)

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

                                             |          | [  0%]   00:00 -> (? left)

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

                                             |          | [  0%]   00:00 -> (? left)

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
---
WARNING: one or more correlations had an edge-case/error and a 1.0 correlation was assigned
(likely due to only having a single row, containing non-NaN values for both correlated features)
Affected correlations:['weeks_absent/actualhrs_main', 'weeks_absent/actualhrs_all', 'actualhrs_main/weeks_absent', 'actualhrs_all/weeks_absent']

NameError: name 'JV_report' is not defined